import React from 'react';
import { Modal, Button, Typography, Space, Tag } from 'antd';
import { PrinterOutlined, FilePdfOutlined, CheckCircleOutlined } from '@ant-design/icons';

const { Title, Text, Paragraph } = Typography;

export default function ProcurementReportModal({
  open,
  onClose,
  query,
  parameters,
  auditReport,
  recommendations
}) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal
      title={
        <Space>
          <FilePdfOutlined style={{ color: '#ef4444' }} />
          <span>Official Public Procurement Standards & Compliance Report</span>
        </Space>
      }
      open={open}
      onCancel={onClose}
      width={980}
      footer={[
        <Button key="close" onClick={onClose}>Close</Button>,
        <Button key="print" type="primary" icon={<PrinterOutlined />} onClick={handlePrint}>
          Print / Export as PDF
        </Button>
      ]}
    >
      <div id="printable-report" style={{ padding: '16px', background: '#fff', color: '#111827' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', borderBottom: '2px solid #111827', paddingBottom: 12 }}>
          <Title level={3} style={{ margin: 0, color: '#111827' }}>PUBLIC PROCUREMENT STANDARDS AUDIT DOSSIER</Title>
          <Text type="secondary">Generated by AI-Powered BIS Standards Engine (SIH26108 Prototype)</Text>
          <br />
          <Text strong>Bureau of Indian Standards / Ministry of Consumer Affairs Compliance Portal</Text>
        </div>

        {/* Section 1: Original Requirement */}
        <div style={{ marginTop: 16 }}>
          <Title level={5} style={{ color: '#111827' }}>1. ORIGINAL PROCUREMENT REQUIREMENT</Title>
          <div style={{ background: '#f3f4f6', padding: 10, borderRadius: 4 }}>
            <Paragraph style={{ margin: 0, fontStyle: 'italic', color: '#1f2937' }}>"{query}"</Paragraph>
          </div>
        </div>

        {/* Section 2: Extracted Technical Specifications */}
        {parameters && (
          <div style={{ marginTop: 16 }}>
            <Title level={5} style={{ color: '#111827' }}>2. VERIFIED SPECIFICATION PARAMETERS</Title>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12.5px' }} border="1">
              <tbody>
                <tr>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', width: '25%', background: '#f9fafb' }}>Product Class:</td>
                  <td style={{ padding: '6px 10px' }}>{parameters.product}</td>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', width: '25%', background: '#f9fafb' }}>Category:</td>
                  <td style={{ padding: '6px 10px' }}>{parameters.category}</td>
                </tr>
                <tr>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', background: '#f9fafb' }}>Procurement Qty:</td>
                  <td style={{ padding: '6px 10px' }}>{parameters.quantity || 'Not specified'}</td>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', background: '#f9fafb' }}>Protections Demanded:</td>
                  <td style={{ padding: '6px 10px' }}>
                    {(parameters.protections_demanded || []).join(', ') || 'Standard mechanical protection'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', background: '#f9fafb' }}>Operating Voltage / Power:</td>
                  <td style={{ padding: '6px 10px' }}>{[parameters.voltage, parameters.power].filter(Boolean).join(' / ') || 'N/A'}</td>
                  <td style={{ padding: '6px 10px', fontWeight: 'bold', background: '#f9fafb' }}>Intended Applications:</td>
                  <td style={{ padding: '6px 10px' }}>
                    {(parameters.applications || []).join(', ') || 'General industrial / public deployment'}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        )}

        {/* Section 3: Statutory Audit Findings */}
        {auditReport && (
          <div style={{ marginTop: 16 }}>
            <Title level={5} style={{ color: '#111827' }}>3. STATUTORY COMPLIANCE & DEFECT AUDIT</Title>
            {auditReport.findings.length > 0 ? (
              auditReport.findings.map((f, i) => (
                <div key={i} style={{ marginBottom: 8, padding: 8, borderLeft: '4px solid #ef4444', background: '#fef2f2' }}>
                  <Text strong style={{ color: '#b91c1c' }}>[{f.tag}] {f.title}</Text>
                  <div style={{ fontSize: '12px', color: '#374151' }}>{f.description}</div>
                  <div style={{ fontSize: '12px', color: '#15803d', fontWeight: 'bold' }}>Required Action: {f.correction}</div>
                </div>
              ))
            ) : (
              <div style={{ padding: 8, background: '#f0fdf4', borderLeft: '4px solid #10b981', color: '#166534', fontSize: '12px' }}>
                ✓ No technical contradictions or mandatory QCO omissions detected. All specifications align with prevailing Bureau of Indian Standards mandates.
              </div>
            )}
          </div>
        )}

        {/* Section 4: Recommended Standards */}
        <div style={{ marginTop: 16 }}>
          <Title level={5} style={{ color: '#111827' }}>4. MANDATORY & RECOMMENDED INDIAN STANDARDS DOSSIER</Title>
          
          {(recommendations || []).map((r, idx) => {
            const std = r.standard;
            const cert = std.certification || {};
            const allied = std.allied_standards || {};
            const amds = (std.amendments || []).map(a => `${a.amendment_no} (${a.year}): ${a.notes}`);

            return (
              <div
                key={idx}
                style={{
                  border: '1px solid #d1d5db',
                  borderRadius: 6,
                  padding: 12,
                  marginBottom: 14,
                  background: '#fafafa'
                }}
              >
                {/* Standard Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #e5e7eb', paddingBottom: 6, marginBottom: 8 }}>
                  <div>
                    <span style={{ fontSize: '14px', fontWeight: 'bold', color: '#1e40af' }}>
                      #{idx + 1} {std.is_code}: {std.title}
                    </span>
                    <div style={{ fontSize: '11px', color: '#4b5563', marginTop: 2 }}>
                      <strong>Edition:</strong> {std.edition || 'Current Revision'} • <strong>Pub Year:</strong> {std.publication_year} • <strong>Reaffirmation:</strong> {std.reaffirmation_date || `Reaffirmed ${std.publication_year + 5}`} • <strong>Status:</strong> {std.status?.toUpperCase() || 'ACTIVE'}
                    </div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <Tag color={cert.scheme === 'CRS' ? 'cyan' : cert.compliance_type?.includes('Mandatory') ? 'red' : 'green'} style={{ fontWeight: 600 }}>
                      {cert.compliance_type || cert.scheme_name}
                    </Tag>
                    <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#0369a1', marginTop: 2 }}>
                      AI Score: {r.ai_relevance_score}%
                    </div>
                  </div>
                </div>

                {/* Primary Standard Role & Scope */}
                <div style={{ background: '#eff6ff', padding: '6px 10px', borderRadius: 4, marginBottom: 6, fontSize: '11.5px', border: '1px solid #bfdbfe' }}>
                  <strong style={{ color: '#1e40af' }}>Primary Manufacturing Specification: </strong>
                  <span style={{ color: '#1e3a8a' }}>{std.primary_standard?.description || std.scope}</span>
                </div>

                {/* Why Recommended */}
                <div style={{ background: '#f8fafc', padding: '6px 10px', borderRadius: 4, marginBottom: 6, fontSize: '11.5px', border: '1px solid #e2e8f0' }}>
                  <strong style={{ color: '#0369a1' }}>Dynamic AI Rationale: </strong>
                  <ul style={{ margin: '4px 0 0 16px', padding: 0, color: '#334155' }}>
                    {(r.why_recommended || []).map((rw, rwIdx) => (
                      <li key={rwIdx}>{rw}</li>
                    ))}
                  </ul>
                </div>

                {/* Statutory Reference */}
                <div style={{ fontSize: '11px', color: '#4b5563', marginBottom: 6 }}>
                  <strong>Official Gazette Reference: </strong> {cert.gazette_reference || cert.mandatory_order} | <strong>Authority: </strong> {cert.regulatory_authority || 'Bureau of Indian Standards'}
                </div>

                {/* Active Amendments */}
                {amds.length > 0 && (
                  <div style={{ fontSize: '11px', color: '#4b5563', marginBottom: 6 }}>
                    <strong>Active Amendments: </strong>
                    {amds.join('; ')}
                  </div>
                )}

                {/* Separately Classified Allied Standards */}
                <div style={{ marginTop: 8, borderTop: '1px dashed #d1d5db', paddingTop: 6 }}>
                  <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#374151', textTransform: 'uppercase', marginBottom: 4 }}>
                    Separately Classified Allied Standards & Normative Taxonomy:
                  </div>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6, fontSize: '10.5px' }}>
                    <div style={{ background: '#f0fdf4', padding: '4px 6px', borderRadius: 4, border: '1px solid #bbf7d0' }}>
                      <strong style={{ color: '#166534' }}>🧪 1. Testing Methods: </strong>
                      {(allied.testing || []).map(t => `${t.is_code} (${t.title || t.description})`).join(', ') || 'Clause 8/9 test protocols'}
                    </div>
                    <div style={{ background: '#fdf2f8', padding: '4px 6px', borderRadius: 4, border: '1px solid #fbcfe8' }}>
                      <strong style={{ color: '#9d174d' }}>🛡️ 2. Safety Norms: </strong>
                      {(allied.safety || []).map(s => `${s.is_code} (${s.title || s.description})`).join(', ') || 'Statutory workplace safety guidelines'}
                    </div>
                    <div style={{ background: '#fffbeb', padding: '4px 6px', borderRadius: 4, border: '1px solid #fde68a' }}>
                      <strong style={{ color: '#854d0e' }}>📐 3. Installation Codes: </strong>
                      {(allied.installation || []).map(i => `${i.is_code} (${i.title || i.description})`).join(', ') || 'Authorized installation practice'}
                    </div>
                    <div style={{ background: '#eff6ff', padding: '4px 6px', borderRadius: 4, border: '1px solid #bfdbfe' }}>
                      <strong style={{ color: '#1e40af' }}>📦 4. Related Products: </strong>
                      {(allied.related_products || []).map(rp => `${rp.is_code} (${rp.title || rp.description})`).join(', ') || 'Complementary components'}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Section 5: Legal Disclaimer */}
        <div style={{ marginTop: 20, padding: 8, background: '#f9fafb', borderTop: '1px solid #e5e7eb' }}>
          <Text type="secondary" style={{ fontSize: '10.5px' }}>
            <strong>DISCLAIMER:</strong> This report is generated by an artificial intelligence recommendation engine designed for SIH26108 demonstration. The scores represent algorithmic relevance and do not constitute an official legal determination by the Bureau of Indian Standards or the Ministry of Consumer Affairs.
          </Text>
        </div>
      </div>
    </Modal>
  );
}
